// src/app/contact/contact.component.ts
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { PortfolioService } from '../services/portfolio.service';
import { CommonModule, AsyncPipe } from '@angular/common';
import { BehaviorSubject } from 'rxjs';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule, AsyncPipe, MatCardModule, MatFormFieldModule, MatInputModule, MatButtonModule],
  templateUrl: './contact.component.html'
})
export class ContactComponent {
  private fb = inject(FormBuilder);
  private service = inject(PortfolioService);

  contactStatus$ = new BehaviorSubject<string>('');
  projectStatus$ = new BehaviorSubject<string>('');

  contactForm = this.fb.group({
    name: ['', Validators.required],
    email: ['', [Validators.required, Validators.email]],
    message: ['', Validators.required]
  });

  projectForm = this.fb.group({
    projTitle: ['', Validators.required],
    projDesc: ['', Validators.required],
    projTags: ['', Validators.required],
    projLinks: ['', Validators.required],
    projImage: [null]
  });

  submitContact() {
    if (this.contactForm.valid) {
      this.service.sendContact(this.contactForm.value).subscribe({
        next: (res) => {
          this.contactStatus$.next(res.message);
          this.contactForm.reset();
        },
        error: () => this.contactStatus$.next('Failed to send message.')
      });
    }
  }

  submitProject() {
    if (this.projectForm.valid) {
      this.projectStatus$.next('Project added successfully (Local Simulation)');
      this.projectForm.reset();
    }
  }

  onFileChange(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.projectForm.patchValue({ projImage: file });
    }
  }
}
<div style="display: flex; flex-direction: column; gap: 30px; max-width: 800px; margin: 0 auto; padding-bottom: 40px;">
  
  <mat-card appearance="outlined">
    <mat-card-header>
      <mat-card-title>Contact Me</mat-card-title>
      <mat-card-subtitle>Have questions or feedback about my site? I’d love to hear from you.</mat-card-subtitle>
    </mat-card-header>
    <mat-card-content style="margin-top: 15px;">
      <form [formGroup]="contactForm" (ngSubmit)="submitContact()" style="display: flex; flex-direction: column; gap: 10px;">
        <mat-form-field appearance="outline">
          <mat-label>Your Name</mat-label>
          <input matInput formControlName="name" aria-label="Your Name" placeholder="Tam Doan">
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Email Address</mat-label>
          <input matInput formControlName="email" type="email" aria-label="Email Address" placeholder="tddoan@students.ntc.edu">
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Message</mat-label>
          <textarea matInput formControlName="message" rows="4" aria-label="Message" placeholder="Write your message here..."></textarea>
        </mat-form-field>

        <button mat-raised-button color="primary" type="submit" [disabled]="contactForm.invalid" style="padding: 24px; font-weight: 600;">
          Send message
        </button>
        
        @if (contactStatus$ | async; as status) {
          <p style="color: green; margin-top: 10px; font-weight: 500;">{{ status }}</p>
        }
      </form>
    </mat-card-content>
  </mat-card>

  <mat-card appearance="outlined">
    <mat-card-header>
      <mat-card-title>Add a New Project</mat-card-title>
      <mat-card-subtitle>Provide the details below to simulate adding a project to the gallery.</mat-card-subtitle>
    </mat-card-header>
    <mat-card-content style="margin-top: 15px;">
      <form [formGroup]="projectForm" (ngSubmit)="submitProject()" style="display: flex; flex-direction: column; gap: 10px;">
        
        <mat-form-field appearance="outline">
          <mat-label>Project Title</mat-label>
          <input matInput formControlName="projTitle" aria-label="Project Title" placeholder="My Awesome Project">
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Project Description</mat-label>
          <textarea matInput formControlName="projDesc" rows="3" aria-label="Project Description" placeholder="Brief description..."></textarea>
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Technologies Used (comma separated)</mat-label>
          <input matInput formControlName="projTags" aria-label="Technologies" placeholder="HTML, CSS, JavaScript">
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Project Links (URLs)</mat-label>
          <input matInput formControlName="projLinks" aria-label="Project Links" placeholder="https://github.com/...">
        </mat-form-field>
        <button mat-raised-button color="accent" type="submit" [disabled]="projectForm.invalid" style="padding: 24px; font-weight: 600;">
          Add project
        </button>
        
        @if (projectStatus$ | async; as status) {
          <p style="color: green; margin-top: 10px; font-weight: 500;">{{ status }}</p>
        }
      </form>
    </mat-card-content>
  </mat-card>

</div>

// portfolio-react/src/components/Contact.jsx
import { useState } from 'react';
import { Card, CardHeader, CardContent, TextField, Button } from '@mui/material';
import { usePortfolio } from '../hooks/usePortfolio';

export default function Contact() {
  const { sendContact } = usePortfolio();
  
  const [contactForm, setContactForm] = useState({ name: '', email: '', message: '' });
  const [contactStatus, setContactStatus] = useState('');

  const [projectForm, setProjectForm] = useState({ projTitle: '', projDesc: '', projTags: '', projLinks: '' });
  const [projectStatus, setProjectStatus] = useState('');

  const handleContactSubmit = async (e) => {
    e.preventDefault();
    if (contactForm.name && contactForm.email && contactForm.message) {
      const res = await sendContact(contactForm);
      setContactStatus(res.message);
      setContactForm({ name: '', email: '', message: '' });
    }
  };

  const handleProjectSubmit = (e) => {
    e.preventDefault();
    if (projectForm.projTitle && projectForm.projDesc && projectForm.projTags && projectForm.projLinks) {
      setProjectStatus('Project added successfully (Local Simulation)');
      setProjectForm({ projTitle: '', projDesc: '', projTags: '', projLinks: '' });
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '30px', maxWidth: '800px', margin: '0 auto', paddingBottom: '40px' }}>
      
      <Card variant="outlined">
        <CardHeader title="Contact Me" subheader="Have questions or feedback about my site? I’d love to hear from you." />
        <CardContent style={{ marginTop: '15px' }}>
          <form onSubmit={handleContactSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
            <TextField label="Your Name" variant="outlined" required
              value={contactForm.name} onChange={e => setContactForm({...contactForm, name: e.target.value})} />
            
            <TextField label="Email Address" type="email" variant="outlined" required
              value={contactForm.email} onChange={e => setContactForm({...contactForm, email: e.target.value})} />
            
            <TextField label="Message" multiline rows={4} variant="outlined" required
              value={contactForm.message} onChange={e => setContactForm({...contactForm, message: e.target.value})} />

            <Button variant="contained" color="primary" type="submit" style={{ padding: '14px', fontWeight: '600' }}
              disabled={!contactForm.name || !contactForm.email || !contactForm.message}>
              Send message
            </Button>
            
            {contactStatus && <p style={{ color: 'green', marginTop: '10px', fontWeight: '500' }}>{contactStatus}</p>}
          </form>
        </CardContent>
      </Card>

      <Card variant="outlined">
        <CardHeader title="Add a New Project" subheader="Provide the details below to simulate adding a project to the gallery." />
        <CardContent style={{ marginTop: '15px' }}>
          <form onSubmit={handleProjectSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
            <TextField label="Project Title" variant="outlined" required
              value={projectForm.projTitle} onChange={e => setProjectForm({...projectForm, projTitle: e.target.value})} />
            
            <TextField label="Project Description" multiline rows={3} variant="outlined" required
              value={projectForm.projDesc} onChange={e => setProjectForm({...projectForm, projDesc: e.target.value})} />
            
            <TextField label="Technologies Used (comma separated)" variant="outlined" required
              value={projectForm.projTags} onChange={e => setProjectForm({...projectForm, projTags: e.target.value})} />

            <TextField label="Project Links (URLs)" variant="outlined" required
              value={projectForm.projLinks} onChange={e => setProjectForm({...projectForm, projLinks: e.target.value})} />

            <Button variant="contained" color="secondary" type="submit" style={{ padding: '14px', fontWeight: '600' }}
              disabled={!projectForm.projTitle || !projectForm.projDesc || !projectForm.projTags || !projectForm.projLinks}>
              Add project
            </Button>
            
            {projectStatus && <p style={{ color: 'green', marginTop: '10px', fontWeight: '500' }}>{projectStatus}</p>}
          </form>
        </CardContent>
      </Card>

    </div>
  );
}
