// src/app/projects/projects.component.ts
import { Component, OnInit, signal, computed, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PortfolioService } from '../services/portfolio.service';

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './projects.component.html'
})
export class ProjectsComponent implements OnInit {
  private service = inject(PortfolioService);
  activeFilter = signal('all');

  // Automatically recalculates when projects() or activeFilter() changes
  filteredProjects = computed(() => {
    const allProjects = this.service.projects();
    if (this.activeFilter() === 'all') return allProjects;
    return allProjects.filter(p => p.technologiesUsed.includes(this.activeFilter()));
  });

  ngOnInit() {
    this.service.loadProjects();
  }

  onFilterChange(event: Event) {
    const value = (event.target as HTMLSelectElement).value;
    this.activeFilter.set(value);
  }
}
<mat-card style="margin-bottom: 30px;">
    <mat-card-header>
        <mat-card-title>My Projects</mat-card-title>
    </mat-card-header>
    <mat-card-content style="margin-top: 15px;">
        <mat-form-field appearance="outline">
            <mat-label>Filter by Tech</mat-label>
            <mat-select (selectionChange)="onFilterChange($event.value)" [value]="'all'">
                <mat-option value="all">All</mat-option>
                <mat-option value="HTML">HTML</mat-option>
                <mat-option value="JavaScript">JavaScript</mat-option>
                <mat-option value="CSS">CSS</mat-option>
            </mat-select>
        </mat-form-field>

        <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 20px; margin-top: 15px;">
            @for (p of filteredProjects$ | async; track p.id) {
                <mat-card style="background-color: #fafafa; border: 1px solid #e5e7eb;">
                    <mat-card-header>
                        <mat-card-title style="font-size: 1.2rem;">{{ p.title }}</mat-card-title>
                    </mat-card-header>
                    <mat-card-content style="margin-top: 10px;">
                        <p>{{ p.description }}</p>
                        <div style="display: flex; gap: 8px; flex-wrap: wrap; margin-top: 15px;">
                            @for (tag of p.technologiesUsed; track tag) {
                                <span style="background: #e0e7ff; color: #3730a3; padding: 4px 10px; border-radius: 12px; font-size: 0.8rem; font-weight: 500;">
                                    {{ tag }}
                                </span>
                            }
                        </div>
                    </mat-card-content>
                </mat-card>
            } @empty {
                <p style="padding: 20px;">No projects match this filter.</p>
            }
        </div>
    </mat-card-content>
</mat-card>

<mat-card style="background-color: #fffbeb; border-left: 5px solid #fbbf24;">
    <mat-card-header>
        <mat-card-title>5 Essential Rules of Cooking</mat-card-title>
    </mat-card-header>
    <mat-card-content style="margin-top: 10px; font-weight: 500;">
        <p>1) Have a good knife</p>
        <p>2) Use fresh ingredients</p>
        <p>3) Cook often to build skill</p>
        <p>4) Use recipes as guides, not strict rules</p>
        <p>5) Develop your own style</p>
    </mat-card-content>
</mat-card>

// portfolio-react/src/components/Projects.jsx
import { useState } from 'react';
import { Card, CardHeader, CardContent, FormControl, InputLabel, Select, MenuItem } from '@mui/material';
import { usePortfolio } from '../hooks/usePortfolio';

export default function Projects() {
  const { projects, loading } = usePortfolio();
  const [filter, setFilter] = useState('all');

  const filteredProjects = filter === 'all' 
    ? projects 
    : projects.filter(p => p.technologiesUsed.includes(filter));

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '30px' }}>
      <Card>
        <CardHeader title="My Projects" />
        <CardContent style={{ marginTop: '15px' }}>
          <FormControl variant="outlined" style={{ minWidth: 200 }}>
            <InputLabel>Filter by Tech</InputLabel>
            <Select 
              value={filter} 
              onChange={(e) => setFilter(e.target.value)} 
              label="Filter by Tech"
            >
              <MenuItem value="all">All</MenuItem>
              <MenuItem value="HTML">HTML</MenuItem>
              <MenuItem value="JavaScript">JavaScript</MenuItem>
              <MenuItem value="CSS">CSS</MenuItem>
              <MenuItem value="Angular">Angular</MenuItem>
              <MenuItem value="PHP">PHP</MenuItem>
              <MenuItem value="MySQL">MySQL</MenuItem>
            </Select>
          </FormControl>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '20px', marginTop: '20px' }}>
            {loading ? <p>Loading projects...</p> : filteredProjects.length > 0 ? (
              filteredProjects.map(p => (
                <Card key={p.id} style={{ backgroundColor: '#fafafa', border: '1px solid #e5e7eb' }}>
                  {/* FIX IS ON THIS LINE BELOW */}
                  <CardHeader title={<span style={{ fontSize: '1.2rem' }}>{p.title}</span>} />
                  <CardContent style={{ marginTop: '10px' }}>
                    <p>{p.description}</p>
                    <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginTop: '15px' }}>
                      {p.technologiesUsed.map(tag => (
                        <span key={tag} style={{ background: '#e0e7ff', color: '#3730a3', padding: '4px 10px', borderRadius: '12px', fontSize: '0.8rem', fontWeight: '500' }}>
                          {tag}
                        </span>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              ))
            ) : (
              <p style={{ padding: '20px' }}>No projects match this filter.</p>
            )}
          </div>
        </CardContent>
      </Card>

      <Card style={{ backgroundColor: '#fffbeb', borderLeft: '5px solid #fbbf24' }}>
        <CardHeader title="5 Essential Rules of Cooking" />
        <CardContent style={{ marginTop: '10px', fontWeight: '500' }}>
          <p>1) Have a good knife</p>
          <p>2) Use fresh ingredients</p>
          <p>3) Cook often to build skill</p>
          <p>4) Use recipes as guides, not strict rules</p>
          <p>5) Develop your own style</p>
        </CardContent>
      </Card>
    </div>
  );
}
